//! Session event types for durable stream serialization.
//!
//! Every event in a session's durable stream is wrapped in a
//! [`SessionEnvelope`] (which is a [`tau_streams::StreamEnvelope`] typed
//! over [`SessionEvent`]).  The envelope carries a schema version, a
//! microsecond timestamp, and the logical source identifier.
//!
//! # Wire format
//!
//! Each envelope is serialized as a single JSON object using the
//! `#[serde(tag = "type", rename_all = "snake_case")]` convention on
//! `SessionEvent`, so every record on the wire looks like:
//!
//! ```json
//! {"v":1,"ts":1700000000000000,"source":"server","type":"user_message","content":"hello"}
//! ```

use serde::{Deserialize, Serialize};
use tau_streams::StreamEnvelope;

// ---------------------------------------------------------------------------
// SessionEvent
// ---------------------------------------------------------------------------

/// A typed event appended to a session's durable stream.
///
/// Variants mirror the structural categories of messages that flow through
/// an agent session: user inputs, assistant outputs, tool interactions, and
/// operational metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SessionEvent {
    /// A message sent by the user.
    UserMessage {
        /// Text content of the message.
        content: String,
        /// Optional file/image attachments (raw JSON blobs for forward
        /// compatibility; today these mirror [`crate::protocol::ChatAttachment`]).
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        attachments: Vec<serde_json::Value>,
    },
    /// A message generated by the assistant / model.
    AssistantMessage {
        /// Text content of the response.
        content: String,
        /// Model identifier that produced this response (e.g. `"claude-sonnet-4-5"`).
        model: String,
    },
    /// A tool call issued by the assistant.
    ToolCall {
        /// Unique identifier for this call (matches the tool-result `call_id`).
        id: String,
        /// Name of the tool being invoked.
        name: String,
        /// Structured arguments passed to the tool.
        input: serde_json::Value,
    },
    /// The result produced by executing a tool.
    ToolResult {
        /// Identifier that links this result back to its [`SessionEvent::ToolCall`].
        call_id: String,
        /// Tool output (raw JSON; may be a string, object, or array).
        output: serde_json::Value,
        /// `true` when the tool returned an error rather than a normal result.
        #[serde(default)]
        is_error: bool,
    },
    /// A system-level message inserted into the session (e.g. "Resumed after
    /// server restart.").  Not part of the LLM context; display-only.
    SystemMessage {
        /// Informational text.
        content: String,
    },
    /// An arbitrary key/value metadata entry associated with the session.
    ///
    /// Used to record session-level facts (project name, cwd, model changes,
    /// …) without requiring a dedicated variant for each one.
    SessionMeta {
        /// Metadata key.
        key: String,
        /// Metadata value.
        value: serde_json::Value,
    },
}

// ---------------------------------------------------------------------------
// SessionEnvelope type alias
// ---------------------------------------------------------------------------

/// A [`StreamEnvelope`] whose payload is a [`SessionEvent`].
pub type SessionEnvelope = StreamEnvelope<SessionEvent>;

// ---------------------------------------------------------------------------
// Helper methods
// ---------------------------------------------------------------------------

impl SessionEvent {
    /// Wrap this event in a [`SessionEnvelope`] with the given `source`
    /// identifier and the current wall-clock timestamp.
    #[must_use]
    pub fn wrap(self, source: impl Into<String>) -> SessionEnvelope {
        let ts = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_micros() as i64;
        StreamEnvelope {
            v: 1,
            ts,
            source: source.into(),
            event: self,
        }
    }

    /// Serialize this event as a single NDJSON line (no trailing newline).
    ///
    /// The returned bytes can be appended directly to a stream as raw data.
    /// Wraps the event using [`Self::wrap`] before serializing.
    ///
    /// # Panics
    ///
    /// Panics if serde serialization fails — which can only happen for types
    /// that implement `Serialize` incorrectly; `SessionEvent` is not one of them.
    #[must_use]
    pub fn to_ndjson_bytes(&self, source: impl Into<String>) -> Vec<u8> {
        let envelope = self.clone().wrap(source);
        serde_json::to_vec(&envelope).expect("SessionEnvelope serialization is infallible")
    }
}

// ---------------------------------------------------------------------------
// TaskEvent
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum TaskEvent {
    Created { title: String, project: Option<String>, priority: i64, tags: Vec<String> },
    Updated { fields: serde_json::Value },
    Assigned { session_id: String, agent_name: Option<String> },
    Dispatched { session_id: String },
    ProgressNote { note: String },
    Completed { result: Option<String> },
    Failed { error: String },
    Blocked { reason: String },
    Unblocked,
    Cancelled { reason: Option<String> },
}

// ---------------------------------------------------------------------------
// TaskEnvelope type alias
// ---------------------------------------------------------------------------

pub type TaskEnvelope = StreamEnvelope<TaskEvent>;

// ---------------------------------------------------------------------------
// TaskEvent helpers
// ---------------------------------------------------------------------------

impl TaskEvent {
    #[must_use]
    pub fn wrap(self, source: impl Into<String>) -> TaskEnvelope {
        let ts = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_micros() as i64;
        StreamEnvelope {
            v: 1,
            ts,
            source: source.into(),
            event: self,
        }
    }

    #[must_use]
    pub fn to_ndjson_bytes(&self, source: impl Into<String>) -> Vec<u8> {
        let envelope = self.clone().wrap(source);
        serde_json::to_vec(&envelope).expect("TaskEnvelope serialization is infallible")
    }
}

// ---------------------------------------------------------------------------
// SystemEvent
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SystemEvent {
    DaemonStarted { version: String, pid: u32 },
    DaemonShutdown { reason: String },
    AgentStarted { agent_name: String, session_id: String },
    AgentStopped { agent_name: String, reason: String },
    ScheduleFired { schedule_id: String, session_id: String },
    SessionCreated { session_id: String, stream_id: String },
    SessionClosed { session_id: String, reason: String },
    Error { context: String, message: String },
}

// ---------------------------------------------------------------------------
// SystemEnvelope type alias
// ---------------------------------------------------------------------------

pub type SystemEnvelope = StreamEnvelope<SystemEvent>;

// ---------------------------------------------------------------------------
// SystemEvent helpers
// ---------------------------------------------------------------------------

impl SystemEvent {
    #[must_use]
    pub fn wrap(self, source: impl Into<String>) -> SystemEnvelope {
        let ts = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_micros() as i64;
        StreamEnvelope {
            v: 1,
            ts,
            source: source.into(),
            event: self,
        }
    }

    #[must_use]
    pub fn to_ndjson_bytes(&self, source: impl Into<String>) -> Vec<u8> {
        let envelope = self.clone().wrap(source);
        serde_json::to_vec(&envelope).expect("SystemEnvelope serialization is infallible")
    }
}

// ---------------------------------------------------------------------------
// CoordinationEvent
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum CoordinationEvent {
    MemberJoined { session_id: String, role: Option<String> },
    MemberLeft { session_id: String },
    Proposal { proposal_id: String, content: serde_json::Value },
    Vote { proposal_id: String, session_id: String, approved: bool },
    Decision { proposal_id: String, outcome: String },
    Broadcast { content: String, sender: String },
}

// ---------------------------------------------------------------------------
// CoordinationEnvelope type alias
// ---------------------------------------------------------------------------

pub type CoordinationEnvelope = StreamEnvelope<CoordinationEvent>;

// ---------------------------------------------------------------------------
// CoordinationEvent helpers
// ---------------------------------------------------------------------------

impl CoordinationEvent {
    #[must_use]
    pub fn wrap(self, source: impl Into<String>) -> CoordinationEnvelope {
        let ts = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_micros() as i64;
        StreamEnvelope {
            v: 1,
            ts,
            source: source.into(),
            event: self,
        }
    }

    #[must_use]
    pub fn to_ndjson_bytes(&self, source: impl Into<String>) -> Vec<u8> {
        let envelope = self.clone().wrap(source);
        serde_json::to_vec(&envelope).expect("CoordinationEnvelope serialization is infallible")
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// Round-trip all `SessionEvent` variants through JSON.
    #[test]
    fn stream_events_roundtrip() {
        let events: Vec<SessionEvent> = vec![
            SessionEvent::UserMessage {
                content: "hello world".to_string(),
                attachments: Vec::new(),
            },
            SessionEvent::AssistantMessage {
                content: "I can help with that.".to_string(),
                model: "claude-sonnet-4-5".to_string(),
            },
            SessionEvent::ToolCall {
                id: "toolu_01XYZ".to_string(),
                name: "bash".to_string(),
                input: serde_json::json!({"command": "ls -la"}),
            },
            SessionEvent::ToolResult {
                call_id: "toolu_01XYZ".to_string(),
                output: serde_json::json!("total 0\ndrwxr-xr-x  2 user user 40 Jan  1 00:00 ."),
                is_error: false,
            },
            SessionEvent::SystemMessage {
                content: "Resumed after server restart.".to_string(),
            },
            SessionEvent::SessionMeta {
                key: "project_name".to_string(),
                value: serde_json::json!("tau"),
            },
        ];

        for event in &events {
            let json = serde_json::to_string(event).expect("serialize");
            let decoded: SessionEvent = serde_json::from_str(&json).expect("deserialize");
            // Verify the type tag round-trips by re-serializing and comparing.
            let rejson = serde_json::to_string(&decoded).expect("re-serialize");
            assert_eq!(json, rejson, "event did not round-trip cleanly");
        }
    }

    /// `ToolCall` event serializes with the expected `type` tag.
    #[test]
    fn tool_call_event_shape() {
        let event = SessionEvent::ToolCall {
            id: "call_abc123".to_string(),
            name: "read_file".to_string(),
            input: serde_json::json!({"path": "/tmp/test.txt"}),
        };

        let json = serde_json::to_string(&event).expect("serialize");
        let val: serde_json::Value = serde_json::from_str(&json).expect("parse");

        assert_eq!(val["type"], "tool_call");
        assert_eq!(val["id"], "call_abc123");
        assert_eq!(val["name"], "read_file");
        assert_eq!(val["input"]["path"], "/tmp/test.txt");

        // Round-trip
        let decoded: SessionEvent = serde_json::from_str(&json).expect("deserialize");
        match decoded {
            SessionEvent::ToolCall { id, name, input } => {
                assert_eq!(id, "call_abc123");
                assert_eq!(name, "read_file");
                assert_eq!(input["path"], "/tmp/test.txt");
            }
            other => panic!("unexpected variant: {other:?}"),
        }
    }

    /// `ToolResult` event serializes with the expected `type` tag and
    /// `is_error` field (including the `false` default case).
    #[test]
    fn tool_result_event_shape() {
        let success = SessionEvent::ToolResult {
            call_id: "call_abc123".to_string(),
            output: serde_json::json!({"lines": 42}),
            is_error: false,
        };
        let error = SessionEvent::ToolResult {
            call_id: "call_abc123".to_string(),
            output: serde_json::json!("permission denied"),
            is_error: true,
        };

        // Success case
        let json_ok = serde_json::to_string(&success).expect("serialize ok");
        let val_ok: serde_json::Value = serde_json::from_str(&json_ok).expect("parse ok");
        assert_eq!(val_ok["type"], "tool_result");
        assert_eq!(val_ok["call_id"], "call_abc123");
        assert_eq!(val_ok["is_error"], false);

        // Error case
        let json_err = serde_json::to_string(&error).expect("serialize err");
        let val_err: serde_json::Value = serde_json::from_str(&json_err).expect("parse err");
        assert_eq!(val_err["type"], "tool_result");
        assert_eq!(val_err["is_error"], true);

        // Round-trip for the error case
        let decoded: SessionEvent = serde_json::from_str(&json_err).expect("deserialize");
        match decoded {
            SessionEvent::ToolResult {
                call_id,
                output,
                is_error,
            } => {
                assert_eq!(call_id, "call_abc123");
                assert_eq!(output, serde_json::json!("permission denied"));
                assert!(is_error);
            }
            other => panic!("unexpected variant: {other:?}"),
        }
    }

    /// Round-trip all `TaskEvent` variants through JSON.
    #[test]
    fn task_events_roundtrip() {
        let events: Vec<TaskEvent> = vec![
            TaskEvent::Created {
                title: "Fix bug".to_string(),
                project: Some("tau".to_string()),
                priority: 1,
                tags: vec!["bug".to_string()],
            },
            TaskEvent::Updated {
                fields: serde_json::json!({"priority": 2}),
            },
            TaskEvent::Assigned {
                session_id: "sess_001".to_string(),
                agent_name: Some("worker".to_string()),
            },
            TaskEvent::Dispatched {
                session_id: "sess_001".to_string(),
            },
            TaskEvent::ProgressNote {
                note: "halfway done".to_string(),
            },
            TaskEvent::Completed {
                result: Some("success".to_string()),
            },
            TaskEvent::Failed {
                error: "timeout".to_string(),
            },
            TaskEvent::Blocked {
                reason: "waiting on upstream".to_string(),
            },
            TaskEvent::Unblocked,
            TaskEvent::Cancelled {
                reason: Some("no longer needed".to_string()),
            },
        ];

        for event in &events {
            let json = serde_json::to_string(event).expect("serialize");
            let decoded: TaskEvent = serde_json::from_str(&json).expect("deserialize");
            let rejson = serde_json::to_string(&decoded).expect("re-serialize");
            assert_eq!(json, rejson, "task event did not round-trip cleanly");
        }
    }

    /// Round-trip all `SystemEvent` variants through JSON.
    #[test]
    fn system_events_roundtrip() {
        let events: Vec<SystemEvent> = vec![
            SystemEvent::DaemonStarted {
                version: "0.1.0".to_string(),
                pid: 12345,
            },
            SystemEvent::DaemonShutdown {
                reason: "SIGTERM".to_string(),
            },
            SystemEvent::AgentStarted {
                agent_name: "worker".to_string(),
                session_id: "sess_001".to_string(),
            },
            SystemEvent::AgentStopped {
                agent_name: "worker".to_string(),
                reason: "completed".to_string(),
            },
            SystemEvent::ScheduleFired {
                schedule_id: "sched_001".to_string(),
                session_id: "sess_002".to_string(),
            },
            SystemEvent::SessionCreated {
                session_id: "sess_003".to_string(),
                stream_id: "stream_abc".to_string(),
            },
            SystemEvent::SessionClosed {
                session_id: "sess_003".to_string(),
                reason: "user disconnected".to_string(),
            },
            SystemEvent::Error {
                context: "agent_manager".to_string(),
                message: "spawn failed".to_string(),
            },
        ];

        for event in &events {
            let json = serde_json::to_string(event).expect("serialize");
            let decoded: SystemEvent = serde_json::from_str(&json).expect("deserialize");
            let rejson = serde_json::to_string(&decoded).expect("re-serialize");
            assert_eq!(json, rejson, "system event did not round-trip cleanly");
        }
    }

    #[test]
    fn coordination_events_roundtrip() {
        let events: Vec<CoordinationEvent> = vec![
            CoordinationEvent::MemberJoined { session_id: "s1".into(), role: Some("worker".into()) },
            CoordinationEvent::MemberLeft { session_id: "s1".into() },
            CoordinationEvent::Proposal { proposal_id: "p1".into(), content: serde_json::json!({"action": "merge"}) },
            CoordinationEvent::Vote { proposal_id: "p1".into(), session_id: "s1".into(), approved: true },
            CoordinationEvent::Decision { proposal_id: "p1".into(), outcome: "approved".into() },
            CoordinationEvent::Broadcast { content: "sync point".into(), sender: "supervisor".into() },
        ];
        for event in &events {
            let json = serde_json::to_string(event).expect("serialize");
            let decoded: CoordinationEvent = serde_json::from_str(&json).expect("deserialize");
            let rejson = serde_json::to_string(&decoded).expect("re-serialize");
            assert_eq!(json, rejson);
        }
    }
}
